CREATE TABLE posts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title VARCHAR NOT NULL,
  author VARCHAR NOT NULL,
  year SMALLINT NOT NULL,
	slug VARCHAR NOT NULL UNIQUE,
	createdat timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updatedat timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  content text NOT NULL,
	user_id uuid NOT NULL DEFAULT auth.uid() references auth.users
);

CREATE POLICY "Enable read posts for all users"
ON "public"."posts"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable all methods for users based on user_id"
ON "public"."posts"
AS PERMISSIVE FOR ALL
TO public
USING (auth.uid() = user_id);

ALTER TABLE "public"."posts" ENABLE ROW LEVEL SECURITY;