CREATE TABLE posts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title VARCHAR NOT NULL,
  author_first_name VARCHAR NOT NULL,
  author_last_name VARCHAR NOT NULL,
  year SMALLINT NOT NULL,
	slug VARCHAR NOT NULL UNIQUE,
	createdat timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updatedat timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  content text NOT NULL,
	user_id uuid DEFAULT auth.uid() references auth.users
);

CREATE POLICY "Enable read posts for all users"
ON "public"."posts"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable all methods for users based on user_id"
ON "public"."posts"
AS PERMISSIVE FOR ALL
TO public
USING (auth.uid() = user_id);

ALTER TABLE "public"."posts" ENABLE ROW LEVEL SECURITY;

-- For strong typing and TypeScript generation
CREATE TYPE user_permission AS ENUM('SUBSCRIBER', 'USER', 'ADMIN');

-- Create a table for public users
CREATE TABLE IF NOT EXISTS users (
  id uuid NOT NULL,
  username text UNIQUE,
  permission user_permission NOT NULL,

  CONSTRAINT username_length check (char_length(username) >= 3),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey
    FOREIGN KEY (id)
    REFERENCES auth.users (id)
    MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table users
  enable row level security;

create policy "Public users are viewable by everyone." on users
  for select using (true);

-- This trigger automatically creates a profile entry when a new user signs up via Supabase Auth.
-- See https://supabase.com/docs/guides/auth/managing-user-data#using-triggers for more details.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (id, permission)
  values (new.id, 'SUBSCRIBER');
  return new;
end;
$$;

-- trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Uploads database
CREATE TABLE IF NOT EXISTS images (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_name text NOT NULL,
  image_path text NOT NULL,
	createdat timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  user_id uuid DEFAULT auth.uid() references auth.users
);

CREATE POLICY "Enable read posts for all users"
ON "public"."images"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable all methods for users based on user_id"
ON "public"."images"
AS PERMISSIVE FOR ALL
TO public
USING (auth.uid() = user_id);

ALTER TABLE "public"."images" ENABLE ROW LEVEL SECURITY;

-- Create Public Storage Bucket for Images
insert into storage.buckets
  (id, name, public)
values
  ('images', 'images', true);